# Generated by Django 6.0.2 on 2026-02-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingtransaction',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
